general_settings:
  master_key: sk-local-admin

model_list:
  # Groq models
  - model_name: groq-llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY
      base_url: os.environ/GROQ_API_BASE

  - model_name: moonshotai/kimi-k2-instruct-0905
    litellm_params:
      model: groq/moonshotai/kimi-k2-instruct-0905
      api_key: os.environ/GROQ_API_KEY
      base_url: os.environ/GROQ_API_BASE

  - model_name: openai-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: os.environ/GROQ_API_KEY
      base_url: os.environ/GROQ_API_BASE
  # openai models
  - model_name: openai-04mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
      base_url: os.environ/OPENAI_API_BASE

  # ollama models
  - model_name: gpt-oss
    litellm_params:
      model: ollama/gpt-oss:20b
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: gemma3
    litellm_params:
      model: ollama/gemma3:4b
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: qwen3-coder
    litellm_params:
      model: ollama/qwen3-coder:latest
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: lfm2.5-thinking
    litellm_params:
      model: ollama/lfm2.5-thinking:1.2b
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: rnj-1
    litellm_params:
      model: ollama/rnj-1:latest
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: deepseek-r1
    litellm_params:
      model: ollama/deepseek-r1:8b
      base_url: os.environ/OLLAMA_BASE_URL

litellm_settings:
  drop_params: true
