general_settings:
  master_key: sk-local-admin
  store_model_in_db: true
  store_prompts_in_spend_logs: true

model_list:
  # Groq models
  - model_name: groq-llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY
      base_url: os.environ/GROQ_API_BASE

  - model_name: moonshotai/kimi-k2-instruct-0905
    litellm_params:
      model: groq/moonshotai/kimi-k2-instruct-0905
      api_key: os.environ/GROQ_API_KEY
      base_url: os.environ/GROQ_API_BASE

  - model_name: openai-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: os.environ/GROQ_API_KEY
      base_url: os.environ/GROQ_API_BASE
  # openai models
  - model_name: openai-04mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
      base_url: os.environ/OPENAI_API_BASE

  # ollama models
  - model_name: gpt-oss
    litellm_params:
      model: ollama/gpt-oss:20b
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: gemma3
    litellm_params:
      model: ollama/gemma3:4b
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: qwen3-coder
    litellm_params:
      model: ollama/qwen3-coder:latest
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: lfm2.5-thinking
    litellm_params:
      model: ollama/lfm2.5-thinking:1.2b
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: rnj-1
    litellm_params:
      model: ollama/rnj-1:latest
      base_url: os.environ/OLLAMA_BASE_URL

  - model_name: deepseek-r1
    litellm_params:
      model: ollama/deepseek-r1:8b
      base_url: os.environ/OLLAMA_BASE_URL

  # ZAI models
  - model_name: glm-4.7-flash
    litellm_params:
      model: openai/glm-4.7-flash
      api_key: os.environ/ZAI_API_KEY
      base_url: os.environ/ZAI_API_BASE

  - model_name: glm-4.5-flash
    litellm_params:
      model: openai/glm-4.5-flash
      api_key: os.environ/ZAI_API_KEY
      base_url: os.environ/ZAI_API_BASE

  # OpenCode free models
  - model_name: glm-5-free
    litellm_params:
      model: opencode/glm-5-free
      api_key: os.environ/OPENCODE_API_KEY
      base_url: os.environ/OPENCODE_API_BASE

  - model_name: minimax-m2.5-free
    litellm_params:
      model: opencode/minimax-m2.5-free
      api_key: os.environ/OPENCODE_API_KEY
      base_url: os.environ/OPENCODE_API_BASE

  - model_name: kimi-k2.5-free
    litellm_params:
      model: opencode/kimi-k2.5-free
      api_key: os.environ/OPENCODE_API_KEY
      base_url: os.environ/OPENCODE_API_BASE

litellm_settings:
  drop_params: true
